version: '3'

vars:
  PACKAGE_NAME:
    sh: grep '^name = ' pyproject.toml | sed 's/name = "\(.*\)"/\1/'
  PACKAGE_TEST_DIR: test
  VENV_DIR: .venv

tasks:
  build:
    desc: Build distribution package
    cmds:
      - task: clean
      - task: test
      - python -m build

  check-version:
    desc: Check version matches git tag in pyproject.toml
    vars:
      TAG:
        sh: git tag -l --points-at HEAD
    cmds:
      - echo "{{.TAG}}" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+"
      - grep 'version = "{{.TAG}}"' pyproject.toml

  clean:
    desc: Clean build artefacts and cache files
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.ruff_cache" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "build" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "dist" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "test" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete
      - find . -type f -name "*.pyo" -delete
      - find . -type f -name ".coverage" -delete

  deploy-prod:
    desc: Deploy package to pypi.org
    cmds:
      - task: build
      - python -m twine upload dist/*

  deploy-test:
    desc: Deploy package to test.pypi.org
    cmds:
      - task: build
      - python -m twine upload --repository testpypi dist/*

  install:
    desc: Install dependencies
    cmds:
      - pip install -Ue ".[dev]"

  lint:
    desc: Lint
    cmds:
      - ruff format
      - ruff check --fix
      - markdownlint -c .markdownlintrc "**/*.md"
      - yamllint -c .yamllint ./

  test:
    desc: Run tests
    cmds:
      - pytest tests/

  validate-local-package:
    desc: Use the local package to install into a clean venv for validation testing
    dir: "{{.PACKAGE_TEST_DIR}}"
    cmds:
      - task: venv-setup
      - ./{{.VENV_DIR}}/bin/pip install -U ../dist/{{.PACKAGE_NAME}}-*.whl
      - ./{{.VENV_DIR}}/bin/{{.PACKAGE_NAME}} --version
      - task: venv-clean

  validate-pypi-package:
    desc: Install the package from test.pypi.org into a clean venv for validation testing
    dir: "{{.PACKAGE_TEST_DIR}}"
    vars:
      TAG:
        sh: git tag -l --points-at HEAD
    cmds:
      - task: venv-setup
      - echo "{{.TAG}}" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+"
      - ./{{.VENV_DIR}}/bin/pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple {{.PACKAGE_NAME}}=={{.TAG}}
      - ./{{.VENV_DIR}}/bin/{{.PACKAGE_NAME}} --version
      - task: venv-clean

  venv-clean:
    desc: Remove the venv
    dir: "{{.PACKAGE_TEST_DIR}}"
    internal: true
    cmds:
      - rm -fr {{.VENV_DIR}}
    silent: true

  venv-setup:
    desc: Create venv for testing
    dir: "{{.PACKAGE_TEST_DIR}}"
    internal: true
    cmds:
      - task: venv-clean
      - python -m venv {{.VENV_DIR}}
      - ./{{.VENV_DIR}}/bin/pip install -qU pip
